USE NEW_DB.PUBLIC;

CREATE OR REPLACE TABLE employees (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING ,
    HIRE_DATE STRING,
    SALARY NUMBER(10,2)
);

CREATE OR REPLACE FILE FORMAT my_csv_format -- Can be named anything
 TYPE = CSV
 FIELD_DELIMITER = ','
 SKIP_HEADER = 1;  -- Assuming the first row is a header
 